### ISSUE TITLE
Multiple Licenses not accepted.

### ISSUE THREAD

**Issue by Draculion** [Brightspace/d2l-license-checker#88]
Attempted to use the following dependency that required 2 liscenses:

_"spdx-ranges@2.1.1": ["MIT","CC-BY-3.0"]_

Doing so would cause the checker to fail in ci with the following stack:

`npx license-checker-ci
ERROR: Uncaught exception. Details:
       {}
Exited with code exit status 1`

Error wasn't helpful at all. Had to do an override exception as a workaround that specified both licenses in another way.

**Comment by jkehres** [comment]
https://github.com/Brightspace/d2l-license-checker/pull/87 should fix this problem.

**Comment by jkehres** [comment]
Fixed in version 3.1.0.
